#!/usr/bin/env python3
"""Write structured data into every page.

Inline rather than injected by JavaScript. Google can read JS injected JSON-LD
but only after rendering, which is slower and less certain. These are static
pages, so the markup may as well be in the HTML.

Generated rather than hand maintained so the shared block cannot drift between
eleven files. Re-run after changing anything below and commit the result.

    python3 tools/build_schema.py
"""
import json, pathlib, re, sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SITE = 'https://padellogan.com.au'
MARK_OPEN = '<!-- structured data: generated by tools/build_schema.py, do not hand edit -->'
MARK_CLOSE = '<!-- /structured data -->'

# The street number keeps its hyphen here. This is machine readable data that
# has to match the Google Business Profile byte for byte, not client facing
# copy, so the house rule on dashes does not apply.
ADDRESS = {
    '@type': 'PostalAddress',
    'streetAddress': '2-22 Golf Course Drive',
    'addressLocality': 'Meadowbrook',
    'addressRegion': 'QLD',
    'postalCode': '4131',
    'addressCountry': 'AU',
}

CLUB = {
    '@type': 'SportsActivityLocation',
    '@id': SITE + '/#club',
    'name': 'Padel Logan',
    'description': ('Padel club at Meadowbrook Golf Club in Logan, south of Brisbane. Four '
                    'championship padel courts, coaching, social sessions and memberships that '
                    'include unlimited golf at Meadowbrook.'),
    'url': SITE + '/',
    'telephone': '+61732996653',
    'email': 'info@padellogan.com.au',
    'image': [SITE + '/assets/img/heroes/hero-memberships.jpg'],
    'logo': SITE + '/assets/img/logo.png',
    'priceRange': '$$',
    'currenciesAccepted': 'AUD',
    'paymentAccepted': 'Credit Card, Debit Card',
    'address': ADDRESS,
    'geo': {'@type': 'GeoCoordinates', 'latitude': -27.6579874, 'longitude': 153.1502002},
    'hasMap': 'https://www.google.com/maps/place/Meadowbrook+Golf+Club',
    'openingHoursSpecification': [{
        '@type': 'OpeningHoursSpecification',
        'dayOfWeek': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        'opens': '06:00', 'closes': '22:00',
    }],
    'parentOrganization': {
        '@type': 'Organization',
        'name': 'Meadowbrook Golf Club',
        'url': 'https://meadowbrookgolfclub.com.au',
    },
    'sameAs': [
        'https://www.instagram.com/padel.logan/',
        'https://www.facebook.com/profile.php?id=61591779035559',
    ],
    'areaServed': [{'@type': 'City', 'name': n} for n in
                   ['Meadowbrook', 'Loganholme', 'Shailer Park', 'Springwood', 'Daisy Hill',
                    'Underwood', 'Rochedale', 'Browns Plains', 'Logan', 'Brisbane']],
    'sport': 'Padel',
}

WEBSITE = {
    '@type': 'WebSite',
    '@id': SITE + '/#website',
    'url': SITE + '/',
    'name': 'Padel Logan',
    'publisher': {'@id': SITE + '/#club'},
    'inLanguage': 'en-AU',
}

TIERS = [
    ('Founding Platinum Membership', 2750, '7 Day Cart Membership at Meadowbrook Golf Club'),
    ('Founding Gold Membership',     2150, '7 Day Walking Membership at Meadowbrook Golf Club'),
    ('Founding Silver Membership',   1500, '5 Day Walking Membership at Meadowbrook Golf Club'),
]

def product(name, price, golf):
    return {
        '@type': 'Product',
        'name': name,
        'description': (f'Twelve month founding membership at Padel Logan. Free off peak court '
                        f'hire, $10 at peak, court bookings two weeks ahead, and unlimited golf '
                        f'on a {golf}.'),
        'brand': {'@type': 'Brand', 'name': 'Padel Logan'},
        'image': SITE + '/assets/img/heroes/hero-memberships.jpg',
        'offers': {
            '@type': 'Offer',
            'url': SITE + '/memberships',
            'price': str(price),
            'priceCurrency': 'AUD',
            'availability': 'https://schema.org/InStock',
            'seller': {'@id': SITE + '/#club'},
        },
    }

def crumbs(trail):
    return {
        '@type': 'BreadcrumbList',
        'itemListElement': [
            {'@type': 'ListItem', 'position': i + 1, 'name': n,
             **({'item': SITE + u} if u else {})}
            for i, (n, u) in enumerate(trail)
        ],
    }

HOME = ('Home', '/')
PAGES = {
    'index.html':            [WEBSITE],
    'memberships.html':      [crumbs([HOME, ('Founding Memberships', None)])] + [product(*t) for t in TIERS],
    'join.html':             [crumbs([HOME, ('Founding Memberships', '/memberships'), ('Apply Online', None)])],
    'contact.html':          [crumbs([HOME, ('Contact', None)])],
    'privacy.html':          [crumbs([HOME, ('Privacy Policy', None)])],
    'terms.html':            [crumbs([HOME, ('Membership Terms', None)])],
    'terms&conditions.html': [crumbs([HOME, ('Court Hire Terms', None)])],
    'welcome.html':          [],
}

def block(extra):
    graph = [CLUB] + extra
    payload = {'@context': 'https://schema.org', '@graph': graph}
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return (f'    {MARK_OPEN}\n'
            f'    <script type="application/ld+json">\n{body}\n    </script>\n'
            f'    {MARK_CLOSE}\n')

def main():
    changed = 0
    for name, extra in PAGES.items():
        p = REPO / name
        if not p.exists():
            print(f'  missing, skipped: {name}'); continue
        s = p.read_text()
        new = block(extra)
        if MARK_OPEN in s:                       # replace the previous block
            s = re.sub(re.escape(MARK_OPEN) + r'[\s\S]*?' + re.escape(MARK_CLOSE) + r'\n?', new, s)
        else:                                    # insert just before </head>
            s = s.replace('</head>', new + '</head>', 1)
        p.write_text(s)
        changed += 1
        types = ', '.join(sorted({e['@type'] for e in extra})) or 'club only'
        print(f'  {name:24} SportsActivityLocation + {types}')
    print(f'\n  {changed} pages written')

if __name__ == '__main__':
    main()
